apiVersion: batch/v1
kind: CronJob
metadata:
  name: trading-bot
spec:
  # Ejecutar cada hora de Lunes a Viernes [cite: 462]
  schedule: "0 * * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bot
            # Imagen optimizada v6-final [cite: 373, 391]
            image: us-central1-docker.pkg.dev/market-oracle-tesis/market-oracle/market-oracle:release
            imagePullPolicy: Always
            env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: alpaca-api-key
            - name: ALPACA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: alpaca-secret-key
            - name: GCP_PROJECT_ID
              value: "market-oracle-tesis"
            - name: GCP_BUCKET_NAME
              value: "market-oracle-tesis-data-lake"
          restartPolicy: OnFailure